### ISSUE TITLE
Generate a queue of papers to be downloaded

### ISSUE THREAD

**Issue by wergstatt** [jawerg/pprkrkn#4]
The general idea is to generate a queue in the database of links to be crawled. The primary source of those links will be recent publications in relevant journals. Which journals are supposed to be relevant will probably be encoded in the journal ranking.

- [x] Generate a queue table of relevant journals.
- [x] Download the first page of article links for queued journals.
- [x] Generate a queue table of links to download.

**Comment by wergstatt** [comment]
- [x] Use a copy statement instead of millions of insertions.
- [x] Release first page restriction.

**Comment by jawerg** [comment]
Before releasing the first-page restriction, we'll have to check whether there is a possibility to investigate whether changes happened to an entry.

**Comment by wergstatt** [comment]
Great Success!
